/* ============================================================================
*  Name     : CRollerCoasterApp from RollerCoasterApp.cpp
*  Part of  : RollerCoaster
*  Created  : 28.12.2004 by Plusplus
* 
*  Implementation notes:
*
*     Initial content was generated by Series 60 Application Wizard.
*  Version  :
*  Copyright: 2004 Plusplus (plusplus AT free.fr)
* ============================================================================
*/

// INCLUDE FILES
#include    "RollerCoasterApp.h"
#include    "RollerCoasterDocument.h"

// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CRollerCoasterApp::AppDllUid()
// Returns application UID
// ---------------------------------------------------------
//
TUid CRollerCoasterApp::AppDllUid() const
    {
    return KUidRollerCoaster;
    }

   
// ---------------------------------------------------------
// CRollerCoasterApp::CreateDocumentL()
// Creates CRollerCoasterDocument object
// ---------------------------------------------------------
//
CApaDocument* CRollerCoasterApp::CreateDocumentL()
    {
    return CRollerCoasterDocument::NewL( *this );
    }

// ================= OTHER EXPORTED FUNCTIONS ==============
//
// ---------------------------------------------------------
// NewApplication() 
// Constructs CRollerCoasterApp
// Returns: created application object
// ---------------------------------------------------------
//
EXPORT_C CApaApplication* NewApplication()
    {
    return new CRollerCoasterApp;
    }

// ---------------------------------------------------------
// E32Dll(TDllReason) 
// Entry point function for EPOC Apps
// Returns: KErrNone: No error
// ---------------------------------------------------------
//
GLDEF_C TInt E32Dll( TDllReason )
    {
    return KErrNone;
    }

// End of File  

