/*
* ============================================================================
*  Name     : CRollerCoasterDocument from RollerCoasterDocument.h
*  Part of  : RollerCoaster
*  Created  : 28.12.2004 by Plusplus
*  Implementation notes:
*     Initial content was generated by Series 60 Application Wizard.
*  Version  :
*  Copyright: 2004 Plusplus (plusplus AT free.fr)
* ============================================================================
*/

// INCLUDE FILES
#include "RollerCoasterDocument.h"
#include "RollerCoasterAppui.h"

// ================= MEMBER FUNCTIONS =======================

// constructor
CRollerCoasterDocument::CRollerCoasterDocument(CEikApplication& aApp)
: CAknDocument(aApp)    
    {
    }

// destructor
CRollerCoasterDocument::~CRollerCoasterDocument()
    {
    }

// EPOC default constructor can leave.
void CRollerCoasterDocument::ConstructL()
    {
    }

// Two-phased constructor.
CRollerCoasterDocument* CRollerCoasterDocument::NewL(
        CEikApplication& aApp)     // CRollerCoasterApp reference
    {
    CRollerCoasterDocument* self = new (ELeave) CRollerCoasterDocument( aApp );
    CleanupStack::PushL( self );
    self->ConstructL();
    CleanupStack::Pop();

    return self;
    }
    
// ----------------------------------------------------
// CRollerCoasterDocument::CreateAppUiL()
// constructs CRollerCoasterAppUi
// ----------------------------------------------------
//
CEikAppUi* CRollerCoasterDocument::CreateAppUiL()
    {
    return new (ELeave) CRollerCoasterAppUi;
    }

// End of File  
